G_Desp/G_Desp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView


urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html')),
    path('cashflow/', include('cashflow.urls')),
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls)
]

G_Desp/account/urls.py
from django.urls import include, path

from . import views
from django.contrib.auth import views as auth_views

app_name = 'account'
urlpatterns = [
	path('sign_in', auth_views.LoginView.as_view(template_name='account/login.html'), name='sign_in'),
	path('sign_up', views.sign_up, name='sign_up'),
	path('sign_out', views.sign_out, name='sign_out'),
	path('user_details', views.user_details, name='user_details'),
    path('request_reset_password', views.request_reset_password, name='request_reset_password'),
    path('reset_password/<key>', views.reset_password, name='reset_password'),
	path('*', include('django.contrib.auth.urls')),
]

G_Desp/cashflow/urls.py
from django.urls import path

from . import views

app_name = 'cashflow'
urlpatterns = [
	path('category_create', views.category_create, name='category_create'),
	path('category_save', views.category_save, name='category_save'),
	path('category_list', views.category_list, name='category_list'),
	path('category_list/', views.category_list, name='category_list'),
	path('category_detail/<int:pk>', views.category_detail, name='category_detail'),
	path('category_edit/<int:pk>', views.category_edit, name='category_edit'),
	path('category_edit/<int:pk>/update', views.category_update, name='category_update'),
	path('category_edit/<int:pk>/delete', views.category_delete, name='category_delete'),
	path('outflow_create', views.outflow_create, name='outflow_create'),
	path('outflow_save', views.outflow_save, name='outflow_save'),
	path('outflow_list', views.outflow_list, name='outflow_list'),
	path('outflow_list/', views.outflow_list, name='outflow_list'),
	path('outflow_detail/<int:pk>', views.outflow_detail, name='outflow_detail'),
	path('outflow_edit/<int:pk>', views.outflow_edit, name='outflow_edit'),
	path('outflow_edit/<int:pk>/update', views.outflow_update, name='outflow_update'),
	path('outflow_edit/<int:pk>/delete', views.outflow_delete, name='outflow_delete'),
	path('inflow_create', views.inflow_create, name='inflow_create'),
	path('inflow_save', views.inflow_save, name='inflow_save'),
	path('inflow_list', views.inflow_list, name='inflow_list'),
	path('inflow_list/', views.inflow_list, name='inflow_list'),
	path('inflow_detail/<int:pk>', views.inflow_detail, name='inflow_detail'),
	path('inflow_edit/<int:pk>', views.inflow_edit, name='inflow_edit'),
	path('inflow_edit/<int:pk>/update', views.inflow_update, name='inflow_update'),
	path('inflow_edit/<int:pk>/delete', views.inflow_delete, name='inflow_delete'),
	path('home', views.home, name='home'),
	path('home/', views.home, name='home'),
	path('report', views.report, name='report'),
	path('', views.home, name='')
]

G_Desp/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <title>Minhas finanças</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'style_sidebar.css' %}">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    {% block stylesheet %}
    {% endblock stylesheet %}
  </head>
  <body>
    <div class="wrapper d-flex align-items-stretch">
      <nav id="sidebar">
        <div class="custom-menu">
          <button type="button" id="sidebarCollapse" class="btn btn-primary">
            <i class="fa fa-bars"></i>
            <span class="sr-only">Toggle Menu</span>
          </button>
        </div>
        <div class="p-4 pt-5">
          <h1><a href="index.html" class="logo">Minhas finanças</a></h1>
          <ul class="list-unstyled components mb-5">
          <!--<li class="active">
        <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Home</a>
        <ul class="collapse list-unstyled" id="homeSubmenu">
        <li>
        <a href="#">Home 1</a>
        </li>
        <li>
        <a href="#">Home 2</a>
        </li>
        <li>
        <a href="#">Home 3</a>
        </li>
        </ul>
        </li>-->
            <!--<li>
              <a href="#">Home</a>
            </li>-->
            <li>
              <a href="{% url 'cashflow:home' %}" data-toggle="" aria-expanded="false" class="dropdown-toggle">Fluxo de caixa</a>
              <ul class="list-unstyled" id="pageSubmenu">
                <li>
                <a href="{% url 'cashflow:category_list' %}">Categorias</a>
                </li>
                <li>
                <a href="{% url 'cashflow:inflow_list' %}">Entradas</a>
                </li>
                <li>
                <a href="{% url 'cashflow:outflow_list' %}">Saídas</a>
                </li>
                <!--
                <li>
                <a href="#">Report</a>
                </li>
                <li>
                <a href="#">Simulator</a>
                </li>-->
              </ul>
            </li>
            <li>
              <a href="{% url 'cashflow:report' %}">Relatório</a>
            </li>
            <li>
              <a href="{% url 'account:user_details' %}">Minhas informações</a>
            </li>
            <!--<li>
              <a href="#">Simulator</a>
            </li>-->
            <li>
              <a href="{% url 'account:sign_out' %}">Sair</a>
            </li>
          </ul>

        <div class="footer"></div>
        </div>
      </nav>

      <div id="content" class="p-4 p-md-5 pt-5">
        <!--<h2 class="mb-4">Bem-vindo, {{ request.user }}!</h2>-->

        {% block content %}
        {% endblock %}

    </div>

    <script src="{% static 'jquery.min.js' %}" type="5e4892f52e5debf832742ce5-text/javascript"></script>
    <script src="{% static 'popper.js' %}" type="5e4892f52e5debf832742ce5-text/javascript"></script>
    <script src="{% static 'bootstrap.min.js' %}" type="5e4892f52e5debf832742ce5-text/javascript"></script>
    <script src="{% static 'main.js' %}" type="5e4892f52e5debf832742ce5-text/javascript"></script>
    <script src="https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js" data-cf-settings="5e4892f52e5debf832742ce5-|49" defer=""></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    {% block scripts %}
    {% endblock scripts %}
  </body>
</html>

G_Desp/templates/index.html
{% load static %}
<!DOCTYPE html>
<!-- saved from url=(0049)https://getbootstrap.com/docs/4.0/examples/cover/ -->
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="https://getbootstrap.com/docs/4.0/assets/img/favicons/favicon.ico">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'cover.css' %}">
    <title>Index</title>
  </head>

  <body class="text-center">

    <div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
      <header class="masthead mb-auto">
        <div class="inner">
          <h3 class="masthead-brand">Marca</h3>
          <nav class="nav nav-masthead justify-content-center">
            <a class="nav-link active" href="#">Index</a>
            <a class="nav-link" href="#">Funcionalidades</a>
            <a class="nav-link" href="#">Contato</a>
          </nav>
        </div>
      </header>

      <main role="main" class="inner cover">
        <h1 class="cover-heading">Sua vida financeira em um unico lugar.</h1>
        <p class="lead">Tenha o controle de sua vida financeira de forma simples e direta.</p>
        <p class="lead">
          <a href="/account/sign_in" class="btn btn-lg btn-primary">Entrar</a>
          <a href="/account/sign_up" class="btn btn-lg btn-success">Criar conta</a>
        </p>
      </main>

      <footer class="mastfoot mt-auto">
        <div class="inner">
          <p>Cover template for <a href="https://getbootstrap.com/">Bootstrap</a>, by <a href="https://twitter.com/mdo">@mdo</a>.</p>
        </div>
      </footer>
    </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="./static/assets/js/vendor/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="./static/popper.min.js"></script>
    <script src="./static/bootstrap.min.js"></script>
  

</body></html>