G_Desp/G_Desp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView


urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html')),
    path('cashflow/', include('cashflow.urls')),
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls)
]

G_Desp/cashflow/urls.py
from django.urls import path

from . import views

app_name = 'cashflow'
urlpatterns = [
	path('category_create', views.category_create, name='category_create'),
	path('category_save', views.category_save, name='category_save'),
	path('category_list', views.category_list, name='category_list'),
	path('category_list/', views.category_list, name='category_list'),
	path('category_detail/<int:pk>', views.category_detail, name='category_detail'),
	path('category_edit/<int:pk>', views.category_edit, name='category_edit'),
	path('category_edit/<int:pk>/update', views.category_update, name='category_update'),
	path('category_edit/<int:pk>/delete', views.category_delete, name='category_delete'),
	path('outflow_create', views.outflow_create, name='outflow_create'),
	path('outflow_save', views.outflow_save, name='outflow_save'),
	path('outflow_list', views.outflow_list, name='outflow_list'),
	path('outflow_list/', views.outflow_list, name='outflow_list'),
	path('outflow_detail/<int:pk>', views.outflow_detail, name='outflow_detail'),
	path('outflow_edit/<int:pk>', views.outflow_edit, name='outflow_edit'),
	path('outflow_edit/<int:pk>/update', views.outflow_update, name='outflow_update'),
	path('outflow_edit/<int:pk>/delete', views.outflow_delete, name='outflow_delete'),
	path('inflow_create', views.inflow_create, name='inflow_create'),
	path('inflow_save', views.inflow_save, name='inflow_save'),
	path('inflow_list', views.inflow_list, name='inflow_list'),
	path('inflow_list/', views.inflow_list, name='inflow_list'),
	path('inflow_detail/<int:pk>', views.inflow_detail, name='inflow_detail'),
	path('inflow_edit/<int:pk>', views.inflow_edit, name='inflow_edit'),
	path('inflow_edit/<int:pk>/update', views.inflow_update, name='inflow_update'),
	path('inflow_edit/<int:pk>/delete', views.inflow_delete, name='inflow_delete'),
	path('home', views.home, name='home'),
	path('home/', views.home, name='home'),
	path('report', views.report, name='report'),
	path('', views.home, name='')
]

G_Desp/cashflow/models.py
import datetime

# Create your models here.
from django.utils import timezone
from django.db import models


class Category(models.Model):
	code = models.IntegerField(null=False)
	name = models.CharField(null=False, max_length=55)
	description = models.CharField(null=False, max_length=255)
	registered_at = models.DateTimeField()
	registered_by = models.CharField(null=False, max_length=55)

	def __str__(self):
		return self.name


class Inflow(models.Model):
	name = models.CharField(null=False, max_length=255)
	value = models.DecimalField(null=False, max_digits=10, decimal_places=2)
	category = models.ForeignKey(Category, on_delete=models.PROTECT)
	registered_at = models.DateTimeField()
	registered_by = models.CharField(null=False, max_length=55)

	def __str__(self):
		return self.name

	def was_registered_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.registered_at <= now


class Outflow(models.Model):
	name = models.CharField(null=False, max_length=255)
	value = models.DecimalField(null=False, max_digits=10, decimal_places=2)
	category = models.ForeignKey(Category, on_delete=models.PROTECT)
	registered_at = models.DateTimeField()
	registered_by = models.CharField(null=False, max_length=55)
	billet_code = models.IntegerField(null=True, blank=True)
	payment_code = models.IntegerField(null=True, blank=True)

	def __str__(self):
		return self.name

	def was_registered_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.registered_at <= now


class Report(models.Model):
	month = models.IntegerField(null=True, blank=True)
	year = models.IntegerField(null=True, blank=True)
	inflow_sum_values = models.DecimalField(null=False, max_digits=10, decimal_places=2, default=0.00)
	outflow_sum_values = models.DecimalField(null=False, max_digits=10, decimal_places=2, default=0.00)
	inflow_outflow_dif_values = models.DecimalField(null=False, max_digits=10, decimal_places=2, default=0.00)
	registered_at = models.DateTimeField()
	registered_by = models.CharField(null=False, max_length=55, default='')

	def calc_dif_values(self):
		try:
			dif = self.inflow_sum_values - self.outflow_sum_values
		except Exception as e:
			raise e
		return dif

G_Desp/cashflow/views.py
from datetime import datetime

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db.models import Avg, Count, Min, ProtectedError, Sum, CharField, Value

from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.template import loader
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from .models import Category, Inflow, Outflow
from .utils import get_first_day_month, get_my_current_balance, get_my_report

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage


# Create your views here.


@login_required(login_url='/account/login')
def category_delete(request, pk):
    try:
        category = Category.objects.filter(
            pk=pk,
            registered_by=request.user.get_username()
        )
        if len(category) > 0:
            was_deleted = Category.objects.filter(
                pk=pk,
                registered_by=request.user.get_username()
            ).delete()
            if was_deleted:
                messages.success(request, 'Category was deleted!')
                return render(request, 'cashflow/category_list.html')
            else:
                messages.error(request, 'An error was ocurred!')
                return render(request, 'cashflow/category_list.html')
        else:
            return HttpResponse('Category not found.')
    except ProtectedError as exc:
        messages.error(
            request,
            "Cannot delete some instances of model, because they are referenced through protected foreign keys."
        )
    except Http404 as e:
        raise HttpResponse('404' + str(e))
    return redirect("/cashflow/category_list")


@login_required(login_url='/account/login')
def category_update(request, pk):
    try:
        code = request.POST['code']
        name = request.POST['name']
        description = request.POST['description']
        registered_at = request.POST['reg_date']
        registered_by = request.user.get_username()

        category = Category.objects.filter(
            pk=pk,
            registered_by=request.user.get_username()
        ).update(
            code=code,
            name=name,
            description=description,
            registered_at=registered_at,
            registered_by=registered_by
        )

        messages.success(request, "Category was updated!")
    except Exception as exc:
        messages.error(request, 'An error was ocurred.')
    return redirect("/cashflow/category_detail/" + str(pk))


@login_required(login_url='/account/login')
def category_edit(request, pk):
    try:
        category = get_object_or_404(
            Category,
            pk=pk,
            registered_by=request.user.get_username()
        )
    except Category.DoesNotExist as e:
        raise Http404('Category does not exist')
    except Http404 as e:
        return HttpResponse('404')
    return render(
        request,
        'cashflow/category_edit.html',
        {
            'category': category,
        }
    )


@login_required(login_url='/account/login')
def category_detail(request, pk):
    try:
        category = get_object_or_404(
            Category,
            pk=pk,
            registered_by=request.user.get_username()
        )
    except Category.DoesNotExist as exc:
        raise Http404('Category does not exist')
    except Http404 as exc:
        return HttpResponse('404')
    return render(request, 'cashflow/category_detail.html', {'category': category})


@login_required(login_url='/account/login')
def category_list(request):
    try:
        categories_inflow_count = 0
        categories_outflow_count = 0

        categories = Category.objects.filter(
            registered_by=request.user.get_username()
        )
        for category in categories:
            categories_inflow = Inflow.objects.filter(
                registered_by=request.user.get_username(),
                category=category
            )
            categories_outflow = Outflow.objects.filter(
                registered_by=request.user.get_username(),
                category=category
            )

            if categories_inflow:
                categories_inflow_count += categories_inflow.count()

            if categories_outflow:
                categories_outflow_count += categories_outflow.count()

    except Category.DoesNotExist as e:
        raise Http404('Category does not exist')
    except Http404 as exc:
        return HttpResponse('404')
    return render(
        request,
        'cashflow/category_list.html',
        {
            'categories': categories,
            'categories_inflow': categories_inflow_count,
            'categories_outflow': categories_outflow_count,
        }
    )


@login_required(login_url='/account/sign_in')
def category_save(request):
    try:
        if request.POST:

            category = Category()
            category.code = request.POST['code']
            category.name = request.POST['name']
            category.description = request.POST['description']
            category.registered_at = request.POST['reg_date']
            category.registered_by = request.user.username
            category.save()


            messages.success(request, "A new category was created!")
    except Exception as exc:
        print(exc)
        messages.error(request, 'Ocorreu um erro' + str(exc))
        return redirect('/cashflow/category_list')
    return redirect('/cashflow/category_list')


@login_required(login_url='/account/sign_in')
def category_create(request):
    try:
        template_name = "category_create"
    except Exception as exc:
        messages.error(request, 'erro')
    return render(
        request, 'cashflow/category_create.html',
    )


@login_required(login_url='/account/login')
def inflow_delete(request, pk):
    try:
        registered_by = request.user.get_username()
        inflow = Inflow.objects.filter(
            pk=pk,
            registered_by=registered_by
        )
        if len(inflow) > 0:
            was_deleted = Inflow.objects.filter(
                pk=pk,
                registered_by=registered_by
            ).delete()
            if was_deleted:
                messages.success(request, 'Inflow was deleted!')
                return render(request, 'cashflow/inflow_list.html')
            else:
                messages.error(request, 'An error was ocurred!')
                return render(request, 'cashflow/inflow_list.html')
        else:
            return HttpResponse('Inflow not found.')
    except Http404 as e:
        raise HttpResponse('404' + str(e))
    return redirect("/cashflow/inflow_list")


@login_required(login_url='/account/login')
def inflow_update(request, pk):
    try:
        name = request.POST['name']
        category = Category.objects.filter(
            registered_by__iexact=request.user.username,
            id__iexact=request.POST['categories']
        )[0]
        registered_at = request.POST['reg_date']
        registered_by = request.user.username
        value = request.POST['value']

        inflow = Inflow.objects.filter(
            pk=pk,
            registered_by=registered_by
        ).update(
            name=name,
            value=value,
            category=category,
            registered_at=registered_at,
            registered_by=registered_by
        )
        messages.success(request, "Inflow was updated!")
    except Exception as exc:
        messages.error(request, 'An error was ocurred.')
    return redirect("/cashflow/inflow_detail/" + str(pk))


@login_required(login_url='/account/login')
def inflow_edit(request, pk):
    try:
        categories = None
        registered_by = request.user.get_username()
        categories = Category.objects.filter(
            registered_by__iexact=request.user.get_username()
        )
        inflow = get_object_or_404(
            Inflow,
            pk=pk,
            registered_by=registered_by
        )
    except Inflow.DoesNotExist as e:
        raise Http404('Inflow does not exist')
    except Http404 as e:
        return HttpResponse('404')
    return render(
        request,
        'cashflow/inflow_edit.html',
        {
            'inflow': inflow,
            'categories': categories,
        }
    )


@login_required(login_url='/account/login')
def inflow_detail(request, pk):
    try:
        registered_by = request.user.get_username()
        inflow = get_object_or_404(
            Inflow,
            pk=pk,
            registered_by=registered_by
        )
    except Inflow.DoesNotExist as exc:
        raise Http404('Inflow does not exist')
    except Http404 as exc:
        return HttpResponse('404')
    return render(request, 'cashflow/inflow_detail.html', {'inflow': inflow})


@login_required(login_url='/account/login')
def inflow_list(request):
    try:

        template_name = 'cashflow/inflow_list.html'
        str_date = get_first_day_month()
        registered_by = request.user.get_username()
        print(str_date)
        inflows = Inflow.objects.filter(
            registered_at__gte=str_date,
            registered_by=registered_by
        )
    except Inflow.DoesNotExist as e:
        raise Http404('Inflow does not exist')
    except Http404 as exc:
        return HttpResponse('404')
    return render(
        request,
        'cashflow/inflow_list.html',
        {
            'inflows': inflows
        }
    )


@login_required(login_url='/account/sign_in')
def inflow_save(request):
    try:
        if request.POST:
            category = Category.objects.filter(
                registered_by__iexact=request.user.username,
                id__iexact=request.POST['categories']
            )[0]

            inflow = Inflow()

G_Desp/cashflow/templates/cashflow/category_create.html
{% extends "base.html" %}

{% block content %}
<div
  class="container-fluid">

<div
  class="card">

    <div
      class="card-header">
      <h2>
        Criar categoria
      </h2>
    </div>

    <div
      class="card-body">

      <form
        action="{% url 'cashflow:category_save' %}"
        method="post">
        {% csrf_token %}

        <div
          class="form-group row">
          <label
            for="code"
            class="col-sm-2 col-form-label">
            Código:
          </label>
          <div
            class="col-sm-4">
            <input
              type="text"
              class="form-control"
              id="code"
              name="code"
              value=""
              required="true">
          </div>

          <label 
            for="name"
            class="col-sm-2 col-form-label">
            Nome:
          </label>
          <div
            class="col-sm-4">
            <input 
              type="text"
              class="form-control"
              id="name"
              name="name" 
              value="" 
              required="true">
          </div>
        </div>

        <div class="form-group row">
          <label 
            for="description"
            class="col-sm-2 col-form-label">
            Descrição:
          </label>
          <div class="col-sm-4">
            <input 
              type="text"
              class="form-control" 
              id="description"
              name="description" 
              value=""
              required="true">
          </div>

          <label
            for="reg_date"
            class="col-sm-2 col-form-label">
            Data:
          </label>
          <div
            class="col-sm-4">
            <input
              type="date"
              class="form-control"
              id="reg_date"
              name="reg_date"
              value=""
              required="true">
          </div>
        </div>
        
        <input 
          class="btn btn-success"
          style="text-align:center;"
          type="submit"
          value="Save">

      </form>
    </div>
</div>

</div>
{% endblock %}

G_Desp/cashflow/templates/cashflow/category_edit.html
{% extends "base.html" %}

{% block content %}

<div class="card">
    <div class="card-header">
      <h2>Editar categoria</h2>
    </div>
    <div class="card-body">
      <form action="{% url 'cashflow:category_update' category.id %}" method="post">
        {% csrf_token %}
        <div class="form-group row">
          <label for="inputEmail3" class="col-sm-2 col-form-label">Código:</label>
          <div class="col-sm-4">
            <input type="text" class="form-control" id="code" value="{{ category.code }}" readonly="true" required="true">
          </div>
          <label for="inputEmail3" class="col-sm-2 col-form-label">Nome:</label>
          <div class="col-sm-4">
            <input type="text" class="form-control" id="name" value="{{ category.name }}" required="true">
          </div>
        </div>
        <div class="form-group row">
          <label for="inputEmail3" class="col-sm-2 col-form-label">Descrição:</label>
          <div class="col-sm-4">
            <input type="text" class="form-control" id="description" value="{{ category.description }}" required="true">
          </div>
          <label for="reg_date" class="col-sm-2 col-form-label">Data:</label>
          <div class="col-sm-4">
            <input type="text" class="form-control" id="reg_date" readonly="true" value='{{ category.registered_at|date:"d/m/Y" }}' required="true">
          </div>
        </div>

        <div class="form-group row">
          <label for="registered_by" class="col-sm-2 col-form-label">Registrado por:</label>
          <div class="col-sm-4">
            <input type="text" class="form-control" id="registered_by" readonly="true" value="{{ category.registered_by }}" required="true">
          </div>
        </div>

        <input class="btn btn-success" style="text-align:center;" type="submit" value="Save">
      </form>
    </div>
</div>

{% endblock %}

G_Desp/cashflow/templates/cashflow/category_list.html
{% extends "base.html" %}

{% block content %}
    <div class="container-fluid container-home">
    <div class="row">
      <div class="col-md-6">
        <h1>Minhas categorias</h1>
      </div>
    </div>

    <div class="row">
      <div class="col-md-2">
          <a class="btn btn-primary" href="{% url 'cashflow:category_create' %}" role="button">Criar categoria</a>
      </div>
    </div>
  </div>
    {% for message in messages %}
        {% if message %}
            <div class="alert alert-info" role="alert">
                {{ message }}
            </div>
        {% endif %}
    {% endfor %}
    <div class="row">
      <div class="col-md-2">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Relacionamentos</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Entradas</td>
              <td>{{ categories_inflow }}</td>
            </tr>
            <tr>
              <td>Saídas</td>
              <td>{{ categories_outflow }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Código</th>
          <th scope="col">Nome</th>
          <th scope="col">Registrado em</th>
          <th scope="col">Registrado por</th>
          <!--<th scope="col">Inflow relations</th>
          <th scope="col">Outflow relations</th>-->
          <th scope="col">Ações</th>
        </tr>
      </thead>
      <tbody>
    {% if categories %}
        
        {% for category in categories %}
        <tr>
            <td><a href="{% url 'cashflow:category_detail' category.id %}">{{ category.code }}</a>
            </td>
            <td>{{ category.name }}</td>
            <td>{{ category.registered_at|date:"d/m/Y" }}</td>
            <td>{{ category.registered_by }}</td>
            <!--<td>{{ categories_inflow }}</td>
            <td>{{ categories_outflow }}</td>-->
            <td>
              <button type="button" class="btn btn-outline">
                <a href="{% url 'cashflow:category_detail' category.id %}">
                  <i class="glyphicon glyphicon-eye-open"></i>
                </a>
              </button>
              <button type="button" class="btn btn-outline">
                <a href="{% url 'cashflow:category_edit' category.id %}">
                  <i class="glyphicon glyphicon-edit"></i>
                </a>
              </button>
              <button type="button" class="btn btn-outline">
                <a href="{% url 'cashflow:category_delete' category.id %}">
                  <i class="glyphicon glyphicon-trash"></i>
                </a>
              </button>
            </td>
        </tr>
        {% endfor %}
        
    {% else %}
        <td>Categorias não encontradas.</td>
    {% endif %}
      </tbody>
    </table>
{% endblock %}

G_Desp/cashflow/templates/cashflow/inflow_create.html
{% extends "base.html" %}

{% block content %}
{% if no_categories %}
  <div class="alert alert-warning" role="alert">
    <p><strong></strong>Você precisa criar ao menos uma categoria.</p>
  </div>
{% else %}
<div class="container-fluid" style="text-align:center;">

  <div class="card">
    <div class="card-header">
      <h2>Criar Entrada</h2>
    </div>
    <div class="card-body">
      <form action="{% url 'cashflow:inflow_save' %}" method="post">
        {% csrf_token %}
        <div class="form-group row">
          <label for="inputEmail3" class="col-sm-2 col-form-label">Name:</label>
          <div class="col-sm-4">
            <input type="text" class="form-control" id="name" name="name" value="" required="true">
          </div>

          <label for="categories">Escolha uma categoria:</label>
          <div class="col-sm-3">
            <select name="categories" class="form-control" id="categories" required="true">
              <option value=""></option>
              {% for category in categories %}
                <option value="{{ category.id }}">{{category}}</option>
              {% endfor %}
            </select>
          </div>

        </div>
        <div class="form-group row">
          <label for="inputEmail3" class="col-sm-2 col-form-label">Data:</label>
          <div class="col-sm-4">
            <input type="date" class="form-control" name="reg_date" id="reg_date" value="" required="true">
          </div>

          <label for="inputEmail3" class="col-sm-2 col-form-label">Valor $:</label>
          <div class="col-sm-4">
            <input type="number" class="form-control" step="any" name="value" id="value" value="0.00" required="true">
          </div>

        </div>
        <input class="btn btn-success" style="text-align:center;" type="submit" value="Salvar">
      </form>
    </div>
  </div>
</div>
{% endif %}
{% endblock %}

G_Desp/cashflow/templates/cashflow/inflow_edit.html
{% extends "base.html" %}

{% block content %}

<div class="card">
    <div class="card-header">
      <h2>Editar entrada</h2>
    </div>
    <div class="card-body">
      <form action="{% url 'cashflow:inflow_update' inflow.id %}" method="post">
        {% csrf_token %}

        <div class="form-group row">
          <label for="inputEmail3" class="col-sm-2 col-form-label">Nome:</label>
          <div class="col-sm-4">
            <input type="text" class="form-control" id="name" name="name" value="{{ inflow.name }}" required="true">
          </div>

          <label for="categories">Escolha uma categoria:</label>
          <div class="col-sm-3">
            <select name="categories" class="form-control" id="categories" required="true">
              <option value=""></option>
              {% for category in categories %}
                <option value="{{ category.id }}">{{category}}</option>
              {% endfor %}
            </select>
          </div>

        </div>
        <div class="form-group row">
          <label for="inputEmail3" class="col-sm-2 col-form-label">Data:</label>
          <div class="col-sm-4">
            <input type="text" class="form-control" name="reg_date" id="reg_date" value='{{ inflow.registered_at|date:"d/m/Y" }}' readonly="true" required="true">
          </div>

          <label for="inputEmail3" class="col-sm-2 col-form-label">Valor $:</label>
          <div class="col-sm-4">
            <input type="number" class="form-control" step="any" name="value" id="value" value="{{ inflow.value }}" required="true">
          </div>

        </div>

        <!--<br>-->
        <input class="btn btn-info" type="submit" value="Salvar">
      </form>
    </div>
</div>
{% endblock %}

G_Desp/cashflow/templates/cashflow/inflow_list.html
{% extends "base.html" %}

{% block content %}
    <div class="container-fluid container-home">
    <div class="row">
      <div class="col-md-4">
        <h1>Minhas Entradas</h1>
      </div>
    </div>
    <div class="row">
      <div class="col-md-2">
        <a class="btn btn-primary" href="{% url 'cashflow:inflow_create' %}" role="button">Criar Entrada</a>
      </div>
    </div>
  </div>
    {% for message in messages %}
        {% if message %}
            <div class="alert alert-info" role="alert">
                {{ message }}
            </div>
        {% endif %}
    {% endfor %}
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Nome</th>
          <th scope="col">Categoria</th>
          <th scope="col">Registrada em</th>
          <th scope="col">Registrada por</th>
          <th scope="col">Valor $</th>
          <th scope="col">Ações</th>
        </tr>
      </thead>
      <tbody>
    {% if inflows %}
        {% for inflow in inflows %}
        <tr>
            <td><a href="{% url 'cashflow:inflow_detail' inflow.id %}">{{ inflow.name }}</a>
            </td>
            <td>{{ inflow.category }}</td>
            <td>{{ inflow.registered_at|date:"d/m/Y" }}</td>
            <td>{{ inflow.registered_by }}</td>
            <td>{{ inflow.value }}</td>
            <td>
              <button type="button" class="btn btn-outline">
                <a href="{% url 'cashflow:inflow_detail' inflow.id %}">
                  <i class="glyphicon glyphicon-eye-open"></i>
                </a>
              </button>
              <button type="button" class="btn btn-outline">
                <a href="{% url 'cashflow:inflow_edit' inflow.id %}">
                  <i class="glyphicon glyphicon-edit"></i>
                </a>
              </button>
              <button type="button" class="btn btn-outline">
                <a href="{% url 'cashflow:inflow_delete' inflow.id %}">
                  <i class="glyphicon glyphicon-trash"></i>
                </a>
              </button>
            </td>
        </tr>
        {% endfor %}
    {% else %}
        <td>Entradas não foram encontradas para o mês atual.</td>
    {% endif %}
      </tbody>
    </table>
{% endblock %}

G_Desp/cashflow/templates/cashflow/outflow_edit.html
{% extends "base.html" %}

{% block content %}
<div class="card">
    <div class="card-header">
      Editar Saída
    </div>
    <div class="card-body">
      <ul>
        <li>{{ outflow.name }}</li>
        <li>{{ outflow.category }}</li>
        <li>{{ outflow.registered_at|date:"d/m/Y" }}</li>
        <li>{{ outflow.registered_by }}</li>
        <li>{{ outflow.value }}</li>
      </ul>
      <form action="{% url 'cashflow:outflow_update' outflow.id %}" method="post">
        {% csrf_token %}
        <label>Nome:</label>
        <input type="text" name="name" id="name" value="{{ outflow.name }}" required="true">
        <!--<br>-->
        <label for="categories">Escolha uma categoria:</label>

        <select name="categories" id="categories" required="true">
          <option value=""></option>
          {% for category in categories %}
            <option value="{{ category.id }}">{{category}}</option>
          {% endfor %}
        </select>
        <!--<br>-->
        <label>Data:</label>
        <input type="date" name="reg_date" id="reg_date" value="{{ outflow.registered_at }}"  required="true">
        <!--<br>-->
        <label>Valor $:</label>
        <input type="number" step="any" name="value" id="value" value="{{ outflow.value }}"  required="true">
        <!--<br>-->
        <input class="btn btn-info" type="submit" value="Salvar">
      </form>
    </div>
</div>
{% endblock %}

G_Desp/cashflow/templates/cashflow/outflow_list.html
{% extends "base.html" %}

{% block content %}
    <div class="container-fluid container-home">
    <div class="row">
      <div class="col-md-4">
        <h1>Minhas Saídas</h1>
      </div>
    </div>

    <div class="row">
      <div class="col-md-2">
        <a class="btn btn-primary" href="{% url 'cashflow:outflow_create' %}" role="button">Criar Saída</a>
      </div>
    </div>
  </div>
    {% for message in messages %}
        {% if message %}
            <div class="alert alert-info" role="alert">
                {{ message }}
            </div>
        {% endif %}
    {% endfor %}
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Nome</th>
          <th scope="col">Categoria</th>
          <th scope="col">Registrado em</th>
          <th scope="col">Registrado por</th>
          <th scope="col">Valor $</th>
          <th scope="col">Ações</th>
        </tr>
      </thead>
      <tbody>
    {% if outflows %}
        {% for outflow in outflows %}
        <tr>
            <td><a href="{% url 'cashflow:outflow_detail' outflow.id %}">{{ outflow.name }}</a>
            </td>
            <td>{{ outflow.category }}</td>
            <td>{{ outflow.registered_at|date:"d/m/Y" }}</td>
            <td>{{ outflow.registered_by }}</td>
            <td>{{ outflow.value }}</td>
            <td>
              <button type="button" class="btn btn-outline">
                <a href="{% url 'cashflow:outflow_detail' outflow.id %}">
                  <i class="glyphicon glyphicon-eye-open"></i>
                </a>
              </button>
              <button type="button" class="btn btn-outline">
                <a href="{% url 'cashflow:outflow_edit' outflow.id %}">
                  <i class="glyphicon glyphicon-edit"></i>
                </a>
              </button>
              <button type="button" class="btn btn-outline">
                <a href="{% url 'cashflow:outflow_delete' outflow.id %}">
                  <i class="glyphicon glyphicon-trash"></i>
                </a>
              </button>
            </td>
        </tr>
        {% endfor %}
    {% else %}
        <td>Saídas não foram encontradas para o mês atual.</td>
    {% endif %}
      </tbody>
    </table>
{% endblock %}